package toberumono.wrf.upgrader;

import java.util.Objects;

/**
 * A simple structure to hold the ID and text of a warning generated by an {@link UpgradeProblemHandler}.
 * 
 * @author Toberumono
 */
public class UpgradeWarning {
	private final String id;
	private final String text;
	
	/**
	 * Constructs a new {@link UpgradeWarning} with the given elements.
	 * 
	 * @param id
	 *            the first element
	 * @param text
	 *            the second element
	 */
	public UpgradeWarning(String id, String text) {
		this.id = id;
		this.text = text;
	}
	
	/**
	 * @return the ID of the {@link UpgradeProblemHandler} that created the {@link UpgradeWarning}
	 */
	public String getID() {
		return id;
	}
	
	/**
	 * @return the text of the warning that the {@link UpgradeWarning} wraps
	 */
	public String getText() {
		return text;
	}
	
	/**
	 * @return a {@link String} containing: "&lt;ID, text&gt;"
	 */
	@Override
	public String toString() {
		return "<" + getID() + ", " + getText() + ">";
	}
	
	@Override
	public int hashCode() {
		return Objects.hash(getID(), getText());
	}
	
	@Override
	public boolean equals(Object o) {
		if (!(o instanceof UpgradeWarning))
			return false;
		UpgradeWarning uw = (UpgradeWarning) o;
		return (getID() == uw.getID() || (getID() != null && getID().equals(uw.getID()))) && (getText() == uw.getText() || (getText() != null && getText().equals(uw.getText())));
	}
	
}
